### ISSUE TITLE
How to deal with a Nadir point of -1?

### ISSUE THREAD

**Issue by ivan-marroquin** [Project-Platypus/Platypus#23]
Hi David,

I get a the following error message:

runfile('C:/Users/IMarroquin/Desktop/toto/Problematic_Script.py', wdir='C:/Users/IMarroquin/Desktop/toto')
Nadir point obtained from maximum of all objectives 1.0

Best hypervolume indicator given by variables :  [-0.02744351 -0.23101299  3.19304276]  =  4.5761e-08
Computed probabilities for Lithofacies 3 : [ 0.03723548  0.0303772   0.93238723]

The addition of the probabilities 0.9999998807907104

Parameters used in inverse third layer with Eps NSGAII :

{'epsilons': 0.040684210526315795, 'iter': 5000}

Nadir point obtained from maximum of all objectives -1.0

Traceback (most recent call last):

  File "<ipython-input-2-41f46feb9e8e>", line 1, in <module>
    runfile('C:/Users/IMarroquin/Desktop/toto/Problematic_Script.py', wdir='C:/Users/IMarroquin/Desktop/toto')

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/IMarroquin/Desktop/toto/Problematic_Script.py", line 439, in <module>
    rstate= np.random.RandomState(seed),

  File "C:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 307, in fmin
    return_argmin=return_argmin,

  File "C:\Anaconda3\lib\site-packages\hyperopt\base.py", line 635, in fmin
    return_argmin=return_argmin)

  File "C:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 320, in fmin
    rval.exhaust()

  File "C:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)

  File "C:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 173, in run
    self.serial_evaluate()

  File "C:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)

  File "C:\Anaconda3\lib\site-packages\hyperopt\base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)

  File "C:/Users/IMarroquin/Desktop/toto/Problematic_Script.py", line 390, in optimize_parameters_inverse_third_layer
    extract_hypervolume_ind[count]= hyp.calculate([solution])

  File "C:\Anaconda3\lib\site-packages\platypus-0.1-py3.6.egg\platypus\indicators.py", line 197, in calculate
    normalize(feasible, self.minimum, self.maximum)

  File "C:\Anaconda3\lib\site-packages\platypus-0.1-py3.6.egg\platypus\core.py", line 1071, in normalize
    raise PlatypusError("objective with empty range")

PlatypusError: objective with empty range

For some reason, I get a Nadir point of Nadir point of -1.0 (see line code 371 - 372). Because of this value, the rest of the code breaks down:

File "C:/Users/IMarroquin/Desktop/toto/Problematic_Script.py", line 390, in optimize_parameters_inverse_third_layer
    extract_hypervolume_ind[count]= hyp.calculate([solution])

What is the meaning of a Nadir point of -1? How should I handle this value so the script continue working? Can I do something like this (between lines 372 and 374):
if (maxi <= 0): #it will account for any potential negative Nadir point value
    maxi= 0 # I force the hypervolume to be zero
else: # the Nadir point is a positive value bigger than zero and the script follows its normal path
 ......

I attached a copy of the script with its input data.

Many thanks,

Ivan

[Problematic_Script.zip](https://github.com/Project-Platypus/Platypus/files/1414652/Problematic_Script.zip)

**Comment by ivan-marroquin** [comment]
I think that I found the source of the problem.
