### ISSUE TITLE
MPIPool fails at the end of the first generation

### ISSUE THREAD

**Issue by EpicSalvation** [Project-Platypus/Platypus#94]
This may be related to Issue #45... I have a custom problem that works fine serially, but fails when using an MPI pool.  I get the exact same issue even when I run simple_mpi.py.  With debugging messages turned on, I see that the first 100 jobs are received, evaluated, and returned by the worker nodes.  At the end of the first generation, all the workers get shut down and it returns an error that seems to be platform-specific.  When running Python 3.6.8 on a Windows 10 workstation with MS MPI 10, I get the following:

> INFO:Platypus:Started pool evaluator
> INFO:Platypus:NSGAII starting
> INFO:Platypus:Closed pool evaluator
> Traceback (most recent call last):
>   File "d:\Google Drive\School\Thesis\Code\Platypus\examples\simple_mpi.py", line 28, in <module>
>     algorithm.run(10000)
>   File "D:\Anaconda3\lib\site-packages\platypus_opt-1.0.2-py3.7.egg\platypus\core.py", line 405, in run
>   File "D:\Anaconda3\lib\site-packages\platypus_opt-1.0.2-py3.7.egg\platypus\algorithms.py", line 181, in step
>   File "D:\Anaconda3\lib\site-packages\platypus_opt-1.0.2-py3.7.egg\platypus\algorithms.py", line 191, in initialize
>   File "D:\Anaconda3\lib\site-packages\platypus_opt-1.0.2-py3.7.egg\platypus\algorithms.py", line 72, in initialize
>   File "D:\Anaconda3\lib\site-packages\platypus_opt-1.0.2-py3.7.egg\platypus\core.py", line 378, in evaluate_all
>   File "D:\Anaconda3\lib\site-packages\platypus_opt-1.0.2-py3.7.egg\platypus\evaluator.py", line 88, in evaluate_all
>   File "D:\Anaconda3\lib\site-packages\platypus_opt-1.0.2-py3.7.egg\platypus\mpipool.py", line 195, in map
>   File "MPI/Comm.pyx", line 1192, in mpi4py.MPI.Comm.recv (c:\miniconda2\conda-bld\mpi4py_1488477230404\work\mpi4py-2.0.0\src\mpi4py.MPI.c:106889)
>   File "MPI/msgpickle.pxi", line 292, in mpi4py.MPI.PyMPI_recv (c:\miniconda2\conda-bld\mpi4py_1488477230404\work\mpi4py-2.0.0\src\mpi4py.MPI.c:43053)
>   File "MPI/msgpickle.pxi", line 143, in mpi4py.MPI.Pickle.load (c:\miniconda2\conda-bld\mpi4py_1488477230404\work\mpi4py-2.0.0\src\mpi4py.MPI.c:41248)
> _pickle.UnpicklingError: invalid load key, '\x02'.

On a Linux HPC (Python 3.6.4), I get a different (but maybe more helpful) message on the last line of the traceback:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 2: invalid start byte

It seems that jobs are being sent and received just fine, but then there is some kind of encoding/decoding error whe results are returned.  I couldn't find any code that is explicitly encoding or decoding messages, though.

**Comment by EpicSalvation** [comment]
For those that may come to this in the future, I solved this by changing `isend()` to `send()` in the `wait()` method of mpipool.py.  Roughly lines 121 and 126.  The isend() method should only be used when a response is expected, which is not typically the case when sending back completed jobs.
